core/urls.py
from django.urls import include, path

from .views import (
    AboutView,
    ConductView,
    HomeView,
    SponsorsView,
    TalkCreateView,
    TalkDeleteSuccessView,
    TalkDeleteView,
    TalkReadView,
    TalkUpdateView,
)

urlpatterns = [
    path(
        '<int:conference_pk>/',
        include(
            [
                path('', HomeView.as_view(), name='home'),
                path('about/', AboutView.as_view(), name='about'),
                path('sponsors/', SponsorsView.as_view(), name='sponsors'),
                path('conduct/', ConductView.as_view(), name='conduct'),
                path('talks/proposal/', TalkCreateView.as_view(), name='talk_create'),
                path('talks/proposal/<int:talk_pk>/', TalkReadView.as_view(), name='talk_read'),
                path('talks/proposal/<int:talk_pk>/update', TalkUpdateView.as_view(), name='talk_update'),
                path('talks/proposal/<int:talk_pk>/delete', TalkDeleteView.as_view(), name='talk_delete'),
                path('talks/proposal/delete_success/', TalkDeleteSuccessView.as_view(), name='talk_delete_success'),
            ]
        ),
    )
]

pyconify/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

core/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

from .choices import CategoryChoices, LevelChoices


class Conference(models.Model):
    year = models.IntegerField(primary_key=True)
    basename = models.CharField(max_length=64)

    def __str__(self):
        return self.get_fullname()

    def get_fullname(self):
        return f'{self.basename} {self.year}'


class Talk(models.Model):
    conference = models.ForeignKey(Conference, on_delete=models.CASCADE)
    proposer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    author_name = models.CharField(max_length=64)
    title = models.CharField(max_length=128)
    abstract = models.TextField()
    category = models.CharField(max_length=32, choices=CategoryChoices.choices)
    level = models.IntegerField(choices=LevelChoices.choices)
    additional_notes = models.TextField(blank=True)

    def get_absolute_url(self):
        return reverse('talk_read', kwargs={'conference_pk': self.conference.year, 'talk_pk': self.pk})

    def get_additional_notes(self):
        return self.additional_notes or '-'

core/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, Form, CharField

from .models import Talk


class TalkCreationForm(ModelForm):
    class Meta:
        model = Talk
        fields = ['author_name', 'title', 'abstract', 'category', 'level', 'additional_notes']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        self.conference_pk = kwargs.pop('conference_pk')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.conference_id = self.conference_pk
        instance.proposer = self.request.user
        if commit:
            instance.save()
        return instance


class TalkUpdateForm(ModelForm):
    class Meta:
        model = Talk
        fields = ['author_name', 'title', 'abstract', 'category', 'level', 'additional_notes']


class TalkDeletionForm(Form):
    confirmation_word = CharField()

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

    def clean_confirmation_word(self):
        data = self.cleaned_data['confirmation_word']
        if data != self.request.user.email:
            raise ValidationError(
                'Invalid confirmation word: %(confirmation_word)s', code='invalid', params={'confirmation_word': data}
            )
        return data

core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, DetailView, FormView, TemplateView, UpdateView
from django.views.generic.edit import SingleObjectMixin
from django.urls import reverse

from .forms import TalkCreationForm, TalkDeletionForm, TalkUpdateForm
from .models import Conference, Talk


class HomeView(DetailView):
    model = Conference
    template_name = 'core/home.html'
    pk_url_kwarg = 'conference_pk'


class AboutView(DetailView):
    model = Conference
    template_name = 'core/about.html'
    pk_url_kwarg = 'conference_pk'


class SponsorsView(DetailView):
    model = Conference
    template_name = 'core/sponsors.html'
    pk_url_kwarg = 'conference_pk'


class ConductView(DetailView):
    model = Conference
    template_name = 'core/conduct.html'
    pk_url_kwarg = 'conference_pk'


class TalkCreateView(LoginRequiredMixin, CreateView):
    model = Talk
    form_class = TalkCreationForm
    template_name = 'core/talk_create.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['conference_pk'] = self.kwargs['conference_pk']
        kwargs['request'] = self.request
        return kwargs

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        conference = get_object_or_404(Conference, pk=self.kwargs['conference_pk'])
        context_data['conference'] = conference
        return context_data


class TalkReadView(LoginRequiredMixin, DetailView):
    pk_url_kwarg = 'talk_pk'
    template_name = 'core/talk_read.html'

    def get_queryset(self):
        return Talk.objects.filter(proposer_id=self.request.user.pk, conference_id=self.kwargs['conference_pk'])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        conference = get_object_or_404(Conference, pk=self.kwargs['conference_pk'])
        context_data['conference'] = conference
        return context_data


class TalkUpdateView(LoginRequiredMixin, UpdateView):
    pk_url_kwarg = 'talk_pk'
    form_class = TalkUpdateForm
    template_name = 'core/talk_update.html'

    def get_queryset(self):
        return Talk.objects.filter(proposer_id=self.request.user.pk, conference_id=self.kwargs['conference_pk'])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        conference = get_object_or_404(Conference, pk=self.kwargs['conference_pk'])
        context_data['conference'] = conference
        return context_data


class TalkDeleteView(LoginRequiredMixin, SingleObjectMixin, FormView):
    pk_url_kwarg = 'talk_pk'
    template_name = 'core/talk_delete.html'
    form_class = TalkDeletionForm

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_queryset(self):
        return Talk.objects.filter(proposer_id=self.request.user.pk, conference_id=self.kwargs['conference_pk'])

    def get_success_url(self):
        return reverse('talk_delete_success', kwargs={'conference_pk': self.kwargs['conference_pk']})

    def form_valid(self, form):
        self.object.delete()
        messages.info(self.request, message=self.object.title, extra_tags='talk_title')
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        conference = get_object_or_404(Conference, pk=self.kwargs['conference_pk'])
        context_data['conference'] = conference
        return context_data


class TalkDeleteSuccessView(LoginRequiredMixin, TemplateView):
    template_name = 'core/talk_delete_success.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        conference = get_object_or_404(Conference, pk=self.kwargs['conference_pk'])
        context_data['conference'] = conference
        return context_data

core/templates/core/about.html
{% extends 'site_base.html' %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'core/css/about.css' %}">
{% endblock %}

{% block title %}
<title>About {{ conference.basename }}</title>
{% endblock %}

{% block hero %}
<header class="hero home">
  <div class="hero-inner container d-flex justify-content-center align-items-center pb-4">
    <h1 class="text-center">About {{ conference.basename }}</h1>
  </div>
</header>
{% endblock %}

core/templates/core/conduct.html
{% extends 'site_base.html' %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'core/css/conduct.css' %}">
{% endblock %}

{% block title %}
<title>Code of Conduct | {{ conference.get_fullname }}</title>
{% endblock %}

{% block hero %}
<header class="hero home">
  <div class="hero-inner container d-flex justify-content-center align-items-center pb-4">
    <h1 class="text-center">Our Code of Conduct</h1>
  </div>
</header>
{% endblock %}

core/templates/core/home.html
{% extends 'site_base.html' %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'core/css/home.css' %}">
{% endblock %}

{% block hero %}
<header class="hero home">
  <div class="hero-inner container d-flex justify-content-center align-items-center pb-4">
    <h1 class="text-center">{{ conference.get_fullname }}</h1>
  </div>
</header>
{% endblock %}

core/templates/core/sponsors.html
{% extends 'site_base.html' %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'core/css/sponsors.css' %}">
{% endblock %}

{% block title %}
<title>Sponsor {{ conference.basename }}</title>
{% endblock %}

{% block hero %}
<header class="hero home">
  <div class="hero-inner container d-flex justify-content-center align-items-center pb-4">
    <h1 class="text-center">Our Sponsors</h1>
  </div>
</header>
<section>
  <div class="text-center">
    <a href="" class="btn btn-black">Sponsor {{ conference.basename }}</a>
  </div>
</section>
{% endblock %}

core/templates/core/talk_create.html
{% extends 'site_base.html' %}

{% load crispy_forms_tags %}

{% block title %}
<title>Propose a Talk | {{ conference.get_fullname }}</title>
{% endblock %}

{% block main %}
<section>
  <div class="container">
    <div class="row justify-content-center align-items-center">
      <div class="col-sm-10 col-lg-8">
        <form method="post">
          {% csrf_token %}
          {{ form | crispy }}
          <div class="text-center">
          <input type="submit" value="Create Talk" class="btn btn-black px-4">
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/talk_delete.html
{% extends 'site_base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'core/css/talk_delete.css' %}">
{% endblock %}

{% block title %}
<title>Delete Talk Proposal | {{ conference.get_fullname }}</title>
{% endblock %}

{% block main %}
<section>
  <div class="container">
    <div class="row justify-content-center align-items-center">
      <div class="col-sm-10 col-lg-8">
        <div class="alert alert-danger p-4" role="alert">
          <p>You are asking to delete your talk, <strong><q>{{ talk.title }}</q></strong>.</p>
          <p>This action is permanent, and cannot be undone. If this is not what you want to do please leave this page at once.</p>
          <p>Enter <strong>{{ user.email }}</strong> in the form field below to confirm you really want to delete this talk.</p>
          <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <div class="text-center">
              <input type="submit" value="Confirm Delete" class="btn btn-red px-4">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/talk_delete_success.html
{% extends 'site_base.html' %}

{% block title %}
<title>Talk Proposal Deleted | {{ conference.get_fullname }}</title>
{% endblock %}

{% block main %}
<section>
  <div class="container">
    {% if messages %}
      {% for message in messages %}
        {% if 'talk_title' in message.tags.split %}
          <div class="alert alert-success" role="alert">
            You've just deleted your talk titled, <strong><q>{{ message }}</q></strong>
          </div>
        {% endif %}
      {% endfor %}
    {% else %}
      <div class="alert alert-success" role="alert">
        Run along, there's nothing to see here! &#x1F47B;
      </div>
    {% endif %}
      </p>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/talk_read.html
{% extends 'site_base.html' %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'core/css/talk_read.css' %}">
{% endblock %}

{% block title %}
<title>Talk Proposal | {{ conference.get_fullname }}</title>
{% endblock %}


{% block main %}
<section>
  <div class="container">

    <h1 class="h3">Talk Detail</h1>

    <span class="heading text-muted">Author Name</span>
    <pre><code>{{ talk.author_name }}</code></pre>

    <span class="heading text-muted">Talk Title</span>
    <pre><code>{{ talk.title }}</code></pre>

    <span class="heading text-muted">Talk Category</span>
    <pre><code>{{ talk.get_category_display }}</code></pre>

    <span class="heading text-muted">Talk Level</span>
    <pre><code>{{ talk.get_level_display }}</code></pre>

    <span class="heading text-muted">Abstract</span>
    <pre><code>{{ talk.abstract }}</code></pre>

    <span class="heading text-muted">Additional Notes</span>
    <pre><code>{{ talk.get_additional_notes }}</code></pre>

    <div class="actions d-flex flex-wrap justify-content-center align-items-center">
      <a
        href="{% url 'talk_update' conference_pk=conference.pk talk_pk=talk.pk %}"
        class="btn btn-black px-4 my-1 mx-2"
        >
        Edit Talk
      </a>
      <a
        href="{% url 'talk_delete' conference_pk=conference.pk talk_pk=talk.pk %}"
        class="btn btn-red px-4 my-1 mx-2"
        >
        Delete Talk
        <small>(confirmation required)</small>
      </a>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/talk_update.html
{% extends 'site_base.html' %}

{% load crispy_forms_tags %}

{% block title %}
<title>Update Talk | {{ conference.get_fullname }}</title>
{% endblock %}

{% block main %}
<section>
  <div class="container">

    <h1 class="h3">Edit Talk</h1>

    <div class="row justify-content-center align-items-center">
      <div class="col-sm-10 col-lg-8">
        <form method="post">
          {% csrf_token %}
          {{ form | crispy }}
          <div class="text-center">
          <input type="submit" value="Update Talk" class="btn btn-black px-4">
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/site_base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block title %}
    <title>{{ conference.get_fullname }}</title>
    {% endblock %}

    <!-- CSS: Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- CSS: site base -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/site_base.css' %}">

    <!-- CSS: extra -->
    {% block extra_css %}
    {% endblock %}


  </head>
  <body class="d-flex flex-column">

    {% block navigation %}
    <nav class="navbar navbar-expand-md">
      <div class="container">
        <a
          class="navbar-brand"
          href="{% url 'home' conference_pk=conference.year %}"
          >
          {{ conference.get_fullname }}
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
        </button>

        <div
          class="collapse navbar-collapse"
          id="navbarSupportedContent"
          >
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a
                class="nav-link"
                href="{% url 'home' conference_pk=conference.year %}"
                >
                Home
              </a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                href="{% url 'about' conference_pk=conference.year %}"
                >
                About
              </a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                href="{% url 'sponsors' conference_pk=conference.year %}"
                >
                Sponsors
              </a>
            </li>
            <li  class="nav-item dropdown">
              <a
                href=""
                class="nav-link dropdown-toggle"
                id="speakingDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
                >
                Speaking
              </a>
              <div class="dropdown-menu" aria-labelledby="speakingDropdown">
                <a
                  class="dropdown-item"
                  href="{% url 'talk_create' conference_pk=conference.year %}"
                  >
                  Propose a Talk
                </a>
              </div>
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                href="{% url 'conduct' conference_pk=conference.year %}"
                >
                Conduct
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% endblock %}

    {% block hero %}
    {% endblock %}

    {% block main %}
    {% endblock %}

    {% block footer %}
    <footer class="mt-auto">
      <div class="footer-inner container d-flex justify-content-center align-items-center">
        <span>Made by <a href="https://twitter.com/mfonism">@mfonism</a></span>
      </div>
    </footer>
    {% endblock %}

    <!-- JS: jQuery + Popper + Bootstrap -->
    <script src="http://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


  </body>
</html>